name: test-workflow
on:
  pull_request:
    types: [opened]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run-stuff
        id: testoutput
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "output-name<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "Some\nMultiline\nOutput" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
      - name: print previous output
        run: echo "out- ${{ steps.testoutput.outputs.output-name }}"
